name: Deploy to GitHub Pages and Cloudflare Pages

on:
  push:
    branches: [ main, master ]
  schedule:
    # Run every day at 00:00 UTC to fetch latest GitHub data
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggers

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build site
        run: npm run build
        env:
          # GitHub token for API access (automatically provided by Actions)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Personal Access Token for higher rate limits
          # Uncomment and add secret if needed:
          # GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          
      - name: Upload artifact for Cloudflare Pages
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy-github-pages:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-cloudflare-pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
          
      - name: List files (debug)
        run: ls -la ./dist
          
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: andrewginns
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'